### ISSUE TITLE
What are the devices we can use with this library?

### ISSUE THREAD

**Issue by nitinjs** [lexruee/pi-switch-python#2]
What are the sender & reciever devices we can use with pi with this library?

**Comment by lexruee** [comment]
@nitinjs Hi! 
The [rc-switch wiki](https://code.google.com/p/rc-switch/wiki/HowTo_Send?tm=6) has a list of [remote power sockets](https://code.google.com/p/rc-switch/wiki/List_KnownDevices) and [rf transmitters](https://code.google.com/p/rc-switch/wiki/List_TransmitterReceiverModules) that work with the rc-switch library. Because pi_switch is just a python wrapper and port of the rc-switch library they *should work* out of the box.

What you basically need is a simple 433Mhz RF transmitter with ASK-modulation like this [one here](http://www.amazon.com/433Mhz-transmitter-receiver-your-Experiment/dp/B00AMB3NCY).
I use this remote power socket here [ger version](http://www.conrad.de/ce/de/product/640472/Funk-Schalter-Zwischenstecker-Reichweite-max-im-Freifeld-30-m-Einsatzort-Innenbereich?ref=searchDetail) / [uk version](http://www.maplin.co.uk/p/remote-controlled-mains-socket-set-single-n78ka).

Hope this helps.
